# Generated by Django 5.0.2 on 2024-03-18 05:42

import django_project.events.validators
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tasting_event', 'Tasting Event'), ('cooking_class', 'Cooking Class')], default='cooking_class', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Limit of 1500 characters', max_length=1500)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, help_text='Upload an image with a resolution of 600x400 pixels and not bigger than 500kb.', keep_meta=True, quality=85, scale=None, size=[400, 600], upload_to='events_images/', validators=[django_project.events.validators.validate_image_size_less_than_500kb])),
            ],
        ),
    ]
