# Generated by Django 5.0.2 on 2024-03-18 14:57

import django_project.events.validators
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, help_text='Upload an image with a resolution of 400x600 pixels and not bigger than 500kb.', keep_meta=True, quality=85, scale=None, size=[400, 600], upload_to='events_images/', validators=[django_project.events.validators.validate_image_size_less_than_500kb]),
        ),
    ]
