# Generated by Django 5.0.2 on 2024-04-07 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('occasions', '0003_alter_seat_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('number_of_tickets', models.PositiveIntegerField(blank=True, null=True)),
                ('type_of_tickets', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('reserved_seats', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='occasions.occasion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
