# Generated by Django 5.0.2 on 2024-04-07 02:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('occasions', '0003_alter_seat_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('ticket_type', models.CharField(max_length=50)),
                ('ticket_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='occasions.occasion')),
            ],
        ),
    ]
