# Generated by Django 5.0.2 on 2024-03-21 04:01

import django.core.validators
import django_project.chefs.validators
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django_project.chefs.validators.validate_name_has_only_letters_and_spaces, django.core.validators.MinLengthValidator(2)])),
                ('bio', models.TextField(help_text='Limit of 600 characters.', max_length=600)),
                ('primary_specialty', models.CharField(choices=[('french_cuisine', 'French Cuisine'), ('italian_cuisine', 'Italian Cuisine'), ('pastry_and_baking', 'Pastry and Baking'), ('asian_cuisine', 'Asian Cuisine'), ('farm_to_table', 'Farm-to-Table'), ('molecular_gastronomy', 'Molecular Gastronomy'), ('vegetarian_and_vegan', 'Vegetarian and Vegan Cuisine'), ('seafood', 'Seafood'), ('bbq_and_grilling', 'BBQ and Grilling'), ('middle_eastern_cuisine', 'Middle Eastern Cuisine'), ('mexican_cuisine', 'Mexican Cuisine'), ('fusion_cuisine', 'Fusion Cuisine'), ('health_and_nutrition', 'Health and Nutrition'), ('street_food', 'Street Food')], max_length=255)),
                ('secondary_specialty', models.CharField(blank=True, choices=[('french_cuisine', 'French Cuisine'), ('italian_cuisine', 'Italian Cuisine'), ('pastry_and_baking', 'Pastry and Baking'), ('asian_cuisine', 'Asian Cuisine'), ('farm_to_table', 'Farm-to-Table'), ('molecular_gastronomy', 'Molecular Gastronomy'), ('vegetarian_and_vegan', 'Vegetarian and Vegan Cuisine'), ('seafood', 'Seafood'), ('bbq_and_grilling', 'BBQ and Grilling'), ('middle_eastern_cuisine', 'Middle Eastern Cuisine'), ('mexican_cuisine', 'Mexican Cuisine'), ('fusion_cuisine', 'Fusion Cuisine'), ('health_and_nutrition', 'Health and Nutrition'), ('street_food', 'Street Food')], max_length=255, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, help_text='Upload an image with a resolution of 400x600 pixels and not bigger than 500kb.', keep_meta=True, quality=85, scale=None, size=[400, 600], upload_to='events_images/', validators=[django_project.chefs.validators.validate_image_size_less_than_500kb])),
            ],
        ),
    ]
