# Generated by Django 5.0.2 on 2024-03-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='primary_specialty',
            field=models.CharField(choices=[('french_cuisine', 'French Cuisine'), ('italian_cuisine', 'Italian Cuisine'), ('pastry_and_baking', 'Pastry & Baking'), ('asian_cuisine', 'Asian Cuisine'), ('farm_to_table', 'Farm-to-Table'), ('molecular_gastronomy', 'Molecular Gastronomy'), ('vegetarian_and_vegan', 'Vegetarian & Vegan'), ('seafood', 'Seafood'), ('bbq_and_grilling', 'BBQ and Grilling'), ('middle_eastern_cuisine', 'Middle Eastern Cuisine'), ('mexican_cuisine', 'Mexican Cuisine'), ('fusion_cuisine', 'Fusion Cuisine'), ('health_and_nutrition', 'Health and Nutrition'), ('street_food', 'Street Food')], max_length=255),
        ),
        migrations.AlterField(
            model_name='chef',
            name='secondary_specialty',
            field=models.CharField(blank=True, choices=[('french_cuisine', 'French Cuisine'), ('italian_cuisine', 'Italian Cuisine'), ('pastry_and_baking', 'Pastry & Baking'), ('asian_cuisine', 'Asian Cuisine'), ('farm_to_table', 'Farm-to-Table'), ('molecular_gastronomy', 'Molecular Gastronomy'), ('vegetarian_and_vegan', 'Vegetarian & Vegan'), ('seafood', 'Seafood'), ('bbq_and_grilling', 'BBQ and Grilling'), ('middle_eastern_cuisine', 'Middle Eastern Cuisine'), ('mexican_cuisine', 'Mexican Cuisine'), ('fusion_cuisine', 'Fusion Cuisine'), ('health_and_nutrition', 'Health and Nutrition'), ('street_food', 'Street Food')], max_length=255, null=True),
        ),
    ]
