# Generated by Django 5.0.2 on 2024-04-09 11:50

import django.core.validators
import django_project.chefs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0003_alter_chef_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='name',
            field=models.CharField(max_length=60, validators=[django_project.chefs.validators.validate_name_has_only_letters_and_spaces, django.core.validators.MinLengthValidator(2)]),
        ),
    ]
