# Generated by Django 5.0.2 on 2024-03-22 04:41

import django_project.venues.validators
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(help_text='Enter the maximum number of people that can attend the venue.')),
                ('description', models.TextField(help_text='Limit of 600 characters.', max_length=600)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, help_text='Upload an image with a resolution of 400x600 pixels and not bigger than 500kb.', keep_meta=True, quality=85, scale=None, size=[400, 600], upload_to='venues_images/', validators=[django_project.venues.validators.validate_image_size_less_than_500kb])),
            ],
        ),
    ]
