# Generated by Django 5.0.2 on 2024-03-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='location',
            field=models.CharField(default='Unknown', help_text='Enter country and city separated by a comma.', max_length=50),
        ),
    ]
