# Generated by Django 5.0.2 on 2024-03-27 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('is_booked', models.BooleanField(default=False)),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='occasions.occasion')),
            ],
            options={
                'unique_together': {('occasion', 'seat_number')},
            },
        ),
    ]
