# Generated by Django 5.0.2 on 2024-03-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occasions', '0002_seat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
    ]
